<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d1c924e7-e763-4d65-a405-3f77950ceec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']/aside[2]/div/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/div[3]/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://maps.gstatic.com/mapfiles/transparent.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/aside[@class=&quot;P65SYh&quot;]/div[@class=&quot;_8KTb-3 undefined&quot;]/div[@class=&quot;YlIatF&quot;]/div[@class=&quot;mh7vik&quot;]/div[@class=&quot;h6Y1+W goEcsM&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;gm-style&quot;]/div[2]/div[2]/div[1]/div[3]/div[2]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/aside[2]/div/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/div[3]/div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://maps.gstatic.com/mapfiles/transparent.png')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div[2]/div/div[3]/div[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
